### ISSUE TITLE
Which number of approvals should be required for a pay request?

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#10]
Currently the config says: 2
Should we change it?

It's a balance of ease of use and security. When more people have to look at the pay and approve it, it is harder to cheat the system, but it also takes longer to approve and one might need to ask more people to take a look at the request.

Maybe we could have/ provide a table of recommended number for number of internal users?

**Comment by CrsiX** [comment]
We discussed this issue. The user must set a value that fits the needs by hand. Additionally, it might need manual changes when the number of users increases/decreases.
But we don't want some kind of option like "_if 25% percent of all users approve it, the request is approved_".
