### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#15]
Instead of printing unhandled exceptions, use a proper logging tool.
Also add reasonable log levels all events.

**Comment by CrsiX** [comment]
This issue was converted into a milestone. Should we close the issue now or make it a part of the milestone?

**Comment by myOmikron** [comment]
Should we log to `/var/log/syslog` or use own files to log into (`/var/log/matebot/matebot.log`)?

**Comment by CrsiX** [comment]
I will close this issue as well as the corresponding milestone. The logging stuff has been set up and is working properly. We might just need to add more logging statements in the code base.

**Remember:** logger names equal the package names they are used in (except for the `runner` or `root` loggers as well as the Telegram framework which uses the module `logging` as well).
