### ISSUE TITLE
Make consumables dynamic

### ISSUE THREAD

**Issue by myOmikron** [hopfenspace/MateBot#17]
In order to allow custom commands for consumables (/ice /pizza /drink) and set their corresponding configurations (how much it costs, etc.) it would be useful to have a section in the config file.

```
"consumables": {
    "ice": {
         "name": "ice",
         "messages": {
              "Ok, enjoy your ice!",
              "Mhmm, yummy!"
         },
         "symbol": "U+1F368",
         "description": "Get an ice.",
         "price": 50,
    },
    [...]
}
```

**Comment by CrsiX** [comment]
So, the `name` field would tell the bot to listen for `/ice`, right? The key in the section might not be relevant. I would therefore prefer `consumables` to be a list:

```json
"consumables": [
     {
         "name": "ice",
         "messages": [
              "Ok, enjoy your ice!",
              "Mhmm, yummy!"
         ],
         "symbol": "U+1F368",
         "description": "Get an ice.",
         "price": 50,
    },
    ...
]
```

Additionally, `messages` must be a list to work this way.
