### ISSUE TITLE
Review /communism

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#25]
Please spend a few minutes on extensive tests of all features that /communism and its callback queries support. Afterwards, the /communism command and the feature in general will be viewed as finished. Note that #7 may be implemented later on. However, as long as the current functionality is not touched, this review stays valid.

This issues was created in favor of #22.

**Comment by gammelalf** [comment]
Spamming `Externals+` or `Externals-` results in this error:
`telegram.error.RetryAfter: Flood control exceeded. Retry in 21 seconds`

**Comment by CrsiX** [comment]
This seems to be hard to fix. Issue #26 is about exactly this bug because it applies to all callback queries in general. While you could potentially send a hundred commands per second in the bot chat, this is not practical. Using callback queries is simply much faster.

Are there any other complains about the communism structure? I would close this issue otherwise.

**Comment by gammelalf** [comment]
I say close it. I still have a problem with communism but since it applies to basicly all commands I'm going to open a general issue #49
