### ISSUE TITLE
List of people one vouches for as shown in /data has wrong name

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#3]
/data command shows a stat `Creditor user`. This stat is meant to show a list of people one vouches for. But "Creditor" is the wrong name for it. I suggest "Debtor" and "users" instead of "user". I am not sure if this naming mistake is in the backend as well.

**Comment by CrsiX** [comment]
In the database, the columns are named `internal` and `external`, so there's no problem. However, the `MateBotUser` class defines the property attribute `creditor` (there's no attribute like `_creditor`). So, it must be renamed in all files where the `MateBotUser.creditor` property attribute is used.

**Comment by gammelalf** [comment]
After looking at the code, I think you explained me this wrong.
If memory serves, you said it is the list of people you vouch for, in which case it is named wrongly.
The code says it is the person who vouches for you, in which case it is named correctly.
If it is the later case: This issue would become a feature request and `/data` should show a list of people you vouch for.

**Comment by gammelalf** [comment]
I close this now and replace it with a feature request, because I misunderstood when I opened this.
