### ISSUE TITLE
Allow a command to have mutually exclusive positional parameters of different types

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#31]
For the easy use of the `/history` command, it should be possible for a user to specify three different variants of positional argument (always one!):

- no argument, the default value for the number of history entries will be used (currently `10`)
- a valid natural number, specifying the number of entries
- a string `json` or `csv` that allows the export of **all** stored transactions of the particular user as JSON or CSV file respectively (because the export of **all** transaction causes problems, see #24)

The usage string could look a bit like this: `/history [length]|[export]` or maybe with additional curved braces `/history ([length] | [export])`

**Comment by CrsiX** [comment]
It looks like `argparse` doesn't allow mutually exclusive positional arguments:

```python
>>> import argparse as a
>>> parser = a.ArgumentParser(prog="test")
>>> group = parser.add_mutually_exclusive_group()
>>> group.add_argument("length", type = int)
Traceback (most recent call last):
  ...
ValueError: mutually exclusive arguments must be optional
>>> 
```

However, the posibility to specify **either** the length **or** the export option **or** nothing for default values seems to be pretty comfortable. We might need to add another parser type for this purpose? The allowed options are very limited (two choices at the moment), though.

**Comment by gammelalf** [comment]
I think you just use argparse wrongly. The error message even says how to fix it: "optional" = "nargs=?"

```python
>>> import argparse as a
>>> parser = a.ArgumentParser()
>>> group = parser.add_mutually_exclusive_group()
>>> group.add_argument("length", type=int, nargs="?")
>>> group.add_argument("export", type=str, nargs="?", choices=("csv", "json"))
```

**Comment by gammelalf** [comment]
Ok there is a problem.
It does allow mutually exclusive positional arguments, but it will only trys to match the first one and breaks if the first doesn't work.

**Comment by gammelalf** [comment]
Ok here is the problem:
You can add multiple positional arguments to a mutually exclusive group, if you make them optional via `nargs`.
BUT:
normally one would use optional arguments (like `--length <length>`) and argparse is made for this.
what we want are two positional argument of which argparse should choose which applies, but it can't do this.

so we could compromise
- with option-strings (`---length` or `--export`)
- length being required for export: `/history [length [export]]`
or we could write a hacky new type/ action

@CrsiX is one of those compromises acceptable or should I write such a type?

**Comment by CrsiX** [comment]
I think option strings (`--length`) are a no-go for any command within the Telegram bot interaction.

Actually, length being required for export might be possible. However, I don't like this idea. The export option is _made_ to get just *all* your transactions.

IMHO, a new type (e.g. `chosen_natural` or whatever you want to call it) that only accepts a limited number of choices (here: `json` and `csv` for now) or any natural number is the right way to go. It is actually not _that_ hacky anymore, because we use the same approach e.g. for [money amount parsing](https://github.com/CrsiX/MateBot/blob/8826bff283b1a372c893cff721b6dcf438d34f15/mate_bot/args/types.py#L53-L88).
