### ISSUE TITLE
Put the maximum of collective operations at a time into the config instead of hardcode it.

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#41]
At the moment, the database layout does not restrict a user in creating collective operations by design. However, the code does [here](https://github.com/CrsiX/MateBot/blob/18887e3e9a3b96bf0cdc08e98c22554026aa4eeb/mate_bot/state/collectives.py#L289-L290) and [here](https://github.com/CrsiX/MateBot/blob/18887e3e9a3b96bf0cdc08e98c22554026aa4eeb/mate_bot/state/collectives.py#L85-L86).

Should we still enforce this limit? It avoids spamming as well as creating and forgetting payment requests / communisms. It might be a good idea to set an upper limit of allowed open collectives at a time for one user in the config. This entry (e.g. `general/max-collectives`) sets the maximum number of open collectives at a time. It could be set to `2` which is fairly enaugh for most circumstances.

**Comment by gammelalf** [comment]
I like the idea of it being configurable. I would set the default to `1`.

**Comment by CrsiX** [comment]
We need some more adjustments and this issue is not totally straightforward. I therefore put it into _Advanced Features_ for now.

**Comment by CrsiX** [comment]
The new API doesn't restrict users in creating any number of "collective operations" (now called "refund requests", "membership polls" and "communisms") and probably won't restrict users in the future, too. However, a client implementation may choose to do so. I will close this issue, as this is not server-related anymore.
