### ISSUE TITLE
Which commands should be available in the internal group only?

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#46]
Currently, no commands and queries are filtered. But we might want to filter which commands can only be accessed in the internal group chat. Performing this operations in other chats should result in an error message.

On the other side, we have some commands (e.g. `/data` and `/history csv`) that are explicitly set to deny requests from non-private chats.

The question is: Which commands should be restricted? In my opinion, any form of consume command (e.g. `/drink` or `/ice`) must be used in the internal group chat. Any other feature can be used in private chats but may yield informational messages in the internal group. It depends whether all other members need / want to know the transaction.

**Comment by gammelalf** [comment]
See my [comment](https://github.com/CrsiX/MateBot/issues/45#issuecomment-696955051) on #45:

**Comment by gammelalf** [comment]
I close this in favor of #49
