### ISSUE TITLE
Too long descriptions/reasons breaking the database call

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#50]
The user can give us a reason or description for various commands, e.g. communisms or sending operations. However, if the length of the description exceeds 255 characters, the command can't be executed properly, because the database column is limited to 255 characters by the type `VARCHAR(255)`.

Should we increase the size of the database columns where this applies to 4096 which is the maximum for any Telegram message? Or should we truncate the message before sending it to the backend? Or should we reply to the user that the supplied message was too long?

**Comment by gammelalf** [comment]
Reply with message to long

**Comment by CrsiX** [comment]
This should be fixed in the type definitions, I think.
