### ISSUE TITLE
Parser should output more informative messages to the user

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#53]
When an optional argument of the type `user` is expected (as e.g. for `/balance`), the parser returns no informative responses to the client.

For example, `/balance foo` results in:

```
No usage applies
/balance [user]
```

This is not quite beautiful or informative. Maybe use `Ambiguous username.` or `No user mentioned`?

**Comment by gammelalf** [comment]
I forgot to close this issue with the commit 4b0f64909c794fd052d3522cc93f736d681d1207 so here I do manually
