### ISSUE TITLE
/help <command> should show the usage string

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#54]
Currently, executing `/help <command>` only shows the description for a command. But it should also produce the usage string for a certain command. This is especially useful for commands like `/history` that support multiple different usages.

**Comment by CrsiX** [comment]
bb88f1d06f46776444ba5a3df5bbd59308315631 seems to fix this issue, does it? @gammelalf

**Comment by gammelalf** [comment]
Yes
