### ISSUE TITLE
Add unittests for the parsing package

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#74]
Adding unittests for the `parsing` package seems to be pretty straightforward to do. The module `test` already contains the things needed to create those tests.

**Comment by gammelalf** [comment]
[Python's doc](https://docs.python.org/3/library/test.html) about the `test` module:
>The test package is meant for internal use by Python only. It is documented for the benefit of the core developers of Python. Any use of this package outside of Python’s standard library is discouraged as code mentioned here can change or be removed without notice between releases of Python.

We should use `unittest` ;P

**Comment by CrsiX** [comment]
Did you take a look into the file? 😂 
We make use of the `unittest` framework in _our own module_ `test`. If you don't want the name, we can rename our module, of course. But I think it's clear that you run the script/module `test` to check the `mate_bot` package, isn't it?

**Comment by CrsiX** [comment]
Input parsing is done in client applications, therefore this won't be part of the API server anymore.
