### ISSUE TITLE
Should there be a timeout for new pay requests when an old was rejected failed?

### ISSUE THREAD

**Issue by gammelalf** [hopfenspace/MateBot#8]
If a pay request was rejected, should the user be unable to post new ones for some time?
This prevents spam, but is it really necessary?

**Comment by CrsiX** [comment]
I think this is a good feature. The maintainer could easily set a value in the config file, e.g. as `community::payment-cooldown` measured in seconds. The last payment has a timestamp stored in the database (`registered`), so this is no much work to do.

**Comment by CrsiX** [comment]
The API won't enforce such restrictions. If this is a wanted feature of a client implementation, the client is free to implement such restrictions. Closing the issue as obsolete.
